name: notedown
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ionicons: ^0.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.7.6
  flutter_expandable_fab: ^2.5.2
  flutter_quill: ^11.5.0
  flutter_slidable: ^4.0.0
  package_info_plus: ^9.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  fonts:
    - family: Hauora
      fonts:
        - asset: assets/fonts/hauora/Hauora-Regular.ttf
        - asset: assets/fonts/hauora/Hauora-Bold.ttf
          weight: 700
